name: Add new issues to yb-voyager 1.0 GA project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
        #Project 10 is yb-voyager 1.0 GA
          project-url: https://github.com/orgs/yugabyte/projects/10
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, triage, GA1.0, enhancement, documentation
          label-operator: OR
