name: Go

on:
  push:
    branches: ['main', '*.*-dev', '*.*.*-dev']
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.23.1"

    - name: Build
      run: |
        cd yb-voyager
        go build -v ./...

    - name: Test
      run: |
        cd yb-voyager
        go test -v  -skip 'TestDDLIssuesInAllVersions' ./... 
    
    - name: Test Issues Against all YB Versions
      env: 
        YB_VERSIONS: '2024.1.3.0-b105,2.21.1.0-b271'
      run: |
        cd yb-voyager
        go test -v -run '^TestDDLIssuesInAllVersions$' ./...
        
    - name: Vet
      run: |
        cd yb-voyager
        go vet ./...

    - name: Run staticcheck
      run: |
        cd yb-voyager
        go install honnef.co/go/tools/cmd/staticcheck@2024.1.1
        staticcheck ./...
