name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        cd yb_migrate
        go build -v ./...

    - name: Test
      run: |
        cd yb_migrate
        go test -v ./...
        
    - name: Vet
      run: |
        cd yb_migrate
        go vet ./...

    - name: Run staticcheck
      run: |
        cd yb_migrate
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
