name: Migration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-migration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: secret
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Run installer script
      run: |
        cd installer_scripts
        #yes | ./yb_migrate_installer__ubuntu.sh

    - name: Test PostgreSQL Connection
      run: |
        sleep 10
        psql "postgresql://postgres:secret@localhost:5432/postgres" -c "SELECT version();"
