name: "MySQL: Migration Tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-mysql-migration-tests:
    strategy:
      matrix:
        version: [2.14.8.0-b17,2.17.2.0-b216,2.16.3.0-b43]
        EXPERIMENTAL_FAST_EXPORT: [0, 1]
    env:
      EXPERIMENTAL_FAST_EXPORT: ${{ matrix.EXPERIMENTAL_FAST_EXPORT }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install python3 and psycopg2
      run: |
        sudo apt install -y python3
        sudo apt install -y libpq-dev
        sudo pip3 install psycopg2

    - name: Run installer script to setup voyager
      run: |
        yes | ./installer_scripts/install-yb-voyager --install-from-local-source
      env:
        ON_INSTALLER_ERROR_OUTPUT_LOG: Y
    
    - name: Fetch and unpack debezium-server
      run: |
        dist_name=debezium-server-latest
        wget -nv "https://github.com/yugabyte/debezium/releases/download/voyager-debezium/${dist_name}.tar.gz"
        sudo mkdir -p /opt/yb-voyager
        sudo tar -xvzf "${dist_name}.tar.gz" -C /opt/yb-voyager/
        rm "${dist_name}".tar.gz

    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        sleep 10

    - name: Test MySQL connection
      run: |
        mysql -uroot -proot -e 'select version();'
    
    - name: Create MySQL user
      run: |
        ./migtests/scripts/mysql/create_mysql_user

    - name: Start YugabyteDB cluster
      run: |
        docker pull yugabytedb/yugabyte:${{ matrix.version }}
        VERSION=${{ matrix.version }} docker-compose -f migtests/setup/yb-docker-compose.yaml up -d
        sleep 20

    - name: Test YugabyteDB connection
      run: |
        psql "postgresql://yugabyte:@127.0.0.1:5433/yugabyte" -c "SELECT version();"

    - name: Create YugabyteDB user
      run: |
        ./migtests/scripts/yugabytedb/create_yb_user

    - name: Enable yb-tserver-n1 name resolution
      run: |
        echo "127.0.0.1	yb-tserver-n1" | sudo tee -a /etc/hosts
        psql "postgresql://yugabyte@yb-tserver-n1:5433/yugabyte" -c "SELECT version();"

    - name: "TEST: mysql-sakila"
      run: migtests/scripts/run-test.sh mysql/sakila

    - name: "TEST: mysql-datatypes"
      run: migtests/scripts/run-test.sh mysql/datatypes

    - name: "TEST: mysql-constraints"
      run: migtests/scripts/run-test.sh mysql/constraints

    - name: "TEST: mysql-case-indexes"
      run: migtests/scripts/run-test.sh mysql/indexes

    - name: "TEST: mysql-functions"
      run: migtests/scripts/run-test.sh mysql/functions

    - name: "TEST: mysql-case-sequences"
      run: migtests/scripts/run-test.sh mysql/sequences

    - name: "TEST: mysql-triggers-procedures"
      run: migtests/scripts/run-test.sh mysql/triggers-procedures

    - name: "TEST: mysql-case-views"
      run: migtests/scripts/run-test.sh mysql/views

    - name: "TEST: mysql-partitions"
      run: migtests/scripts/run-test.sh mysql/partitions

    - name: "TEST: mysql-sample-chinook"
      run: migtests/scripts/run-test.sh mysql/chinook

    - name: "TEST: mysql-reserved-words"
      run: migtests/scripts/run-test.sh mysql/reserved-words
